---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
custom_preview: true
custom_preview_endpoint: http://ykjfu4vbkro6oq.updates.forestryutils.com:8080
custom_preview_url: http://ykjfu4vbkro6oq.p.forestryutils.com:8080
build:
  preview_command: bundle exec jekyll serve --port 8080 --host 0.0.0.0
